CS_MVC4/Controllers/BasicController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

using RadPdf.Web.UI;

namespace CS_MVC4.Controllers
{
    public class BasicController : Controller
    {
        //
        // GET: /Basic/

        public ActionResult Index()
        {
            // Get PDF as byte array from file (or database, browser upload, remote storage, etc)
            byte[] pdfData = System.IO.File.ReadAllBytes(Server.MapPath("~/Data/RadPdfSampleForm.pdf"));

            // Create RAD PDF control
            PdfWebControl pdfWebControl1 = new PdfWebControl();

            // Setup pdfWebControl1 with any properties which must be called before CreateDocument (optional)
            // e.g. pdfWebControl1.RenderDpi = 144;

            // Create document from PDF data
            pdfWebControl1.CreateDocument("Document Name", pdfData);

            // Put control in ViewBag
            ViewBag.PdfWebControl1 = pdfWebControl1;

            return View();
        }

    }
}

CS_MVC4/Controllers/CustomizedController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

using RadPdf.Web.UI;

namespace CS_MVC4.Controllers
{
    public class CustomizedController : Controller
    {
        //
        // GET: /Customized/

        public ActionResult Index()
        {
            // Get PDF as byte array from file (or database, browser upload, remote storage, etc)
            byte[] pdfData = System.IO.File.ReadAllBytes(Server.MapPath("~/Data/RadPdfSampleForm.pdf"));

            // Create RAD PDF control
            PdfWebControl pdfWebControl1 = new PdfWebControl();

            // Setup pdfWebControl1 with any properties which must be called before CreateDocument (optional)
            // e.g. pdfWebControl1.RenderDpi = 144;

            // Create document from PDF data
            pdfWebControl1.CreateDocument("Document Name", pdfData);

            // Put control in ViewBag
            ViewBag.PdfWebControl1 = pdfWebControl1;

            return View();
        }

    }
}

CS_MVC4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CS_MVC4.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

CS_MVC4/Views/Basic/Index.cshtml
@using System.Web.UI.WebControls;

@using RadPdf.Web.UI;

@*
To use the Client API, the following code must be in the <head> element of your View's HTML:
@Html.Raw(RadPdf.Web.UI.PdfWebControl.RenderHead())

See: /Views/Shared/_Layout.cshtml
*@

@{
	ViewBag.Title = "RAD PDF Basic Sample";

	// Get web control from ViewBag
	PdfWebControl pdfWebControl1 = ViewBag.PdfWebControl1;

	// Set control's properties
	pdfWebControl1.ID = "PdfWebControl1"; // Important if Client API is to be used!
	pdfWebControl1.Height = new Unit("600px");
	pdfWebControl1.Width = new Unit("100%");

	// Render web control to body
	@Html.Raw(pdfWebControl1.RenderControl())
}

CS_MVC4/Views/Customized/Index.cshtml
@using System.Web.UI.WebControls;

@using RadPdf.Web.UI;

@*
This page relies on the following code being in the <head> element of your View's HTML:
@Html.Raw(RadPdf.Web.UI.PdfWebControl.RenderHead())

See: /Views/Shared/_Layout.cshtml
*@

@{
	ViewBag.Title = "RAD PDF Customized Sample";

	const string PdfWebControlID = "PdfWebControl1";
}

<script type="text/javascript">
	var api = null;
	var isDownload = false;

	function showViewInformation(view)
	{
		// Show page information
		document.getElementById("pageInformation").innerHTML = "Page " + view.page + " of " + api.getPageCount();
	}

	function initRadPdf()
	{
		// Get id
		var id = "@Html.Encode(PdfWebControlID)";

		// Get api instance
		api = new PdfWebControlApi(id);

		// Attach listeners
		api.addEventListener(
			"viewChanged", 
			function(evt) {
				// Show new view information
				showViewInformation(evt.view);
			}
			);
		api.addEventListener(
			"printing", 
			function(evt) {
				// To cancel printing, we would return false or set evt.cancel = true
				return true;
			}
			);
		api.addEventListener(
			"saved",
			function(evt) {
				// We don't want to show this prompt if we initiated a download
				if (!isDownload) {
					window.alert("Save completed.");
				}
			}
			);

		// Initially show view information
		showViewInformation(api.getView());
	}

	// Additional Code Samples
	function fillOutForm()
	{
		if(api)
		{
			// Get text fields
			var fFirstName = api.getField("First Name");
			var fLastName = api.getField("Last Name");
			var fCreditCardNumber = api.getField("Credit Card Number");
			// Set text values (if the field was found)
			if( fFirstName )
			{
				fFirstName.setProperties( { "value" : "John" } );
			}
			if( fLastName )
			{
				fLastName.setProperties( { "value" : "Smith" } );
			}
			if( fCreditCardNumber )
			{
				fCreditCardNumber.setProperties( { "value" : "5555555555554444" } );
			}

			// Get radio fields
			var fProductTypes = api.getFields("Product Type");
			// Set radio field
			if( fProductTypes )
			{
				// Find and check field with the export value "1"
				for( var i = 0; i < fProductTypes.length; i++ )
				{
					if( fProductTypes[i].getProperties()["exportValue"] == "1" )
					{
						fProductTypes[i].setProperties( { "checked" : true } );
					}
				}
			}

			// Get checkbox field
			var fProductSupport = api.getField("Product Support");
			// Set checkbox field
			if( fProductSupport )
			{
				fProductSupport.setProperties( { "checked" : true } );
			}

			// Get combo field
			var fCardType = api.getField("Card Type");
			// Set combo field
			if( fCardType )
			{
				fCardType.setProperties( { "value" : "MasterCard" } );
			}

			// Get list field
			var fProductOptions = api.getField("Product Options");
			// Set combo field
			if( fProductOptions )
			{
				fProductOptions.setProperties( { "value" : "With PDF Extension" } );
			}
		}
	}
	function watermarkPages()
	{
		if(api)
		{
			//Loop through all pages
			for( var i = 1; i <= api.getPageCount(); i++ )
			{
				//Add watermark object
				var obj = api.getPage(i).addObject(api.ObjectType.TextShape, 50, 50, 750, 120);

				//Set watermark properties
				obj.setProperties(
					{
					"text" : "WATERMARK", 
					"opacity" : 50, 
					"font" : 
						{
						"name" : "Arial",
						"color" : "#ff0000",
						"size" : 110,
						"bold" : true,
						"italic" : false,
						"underline" : false
						},
					"changeable" : false,
					"deletable" : false,
					"hideFocusOutline" : true,
					"movable" : false,
					"resizable" : false,
					"stylable" : false
					} );
			}
		}
	}
	function zoomTo75()
	{
		if(api)
		{
			api.setView( { "zoom" : 75 } );
		}
	}
</script>

<table cellpadding="2" cellspacing="0" width="100%">
	<thead>
		<tr style="font-size:1.2em;">
			<td width="33%">File Operations</td>
			<td width="33%">Activate Tools</td>
			<td width="33%">Additional Samples</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<button onclick="if(api){isDownload=false;api.save();}return false;">Save</button><br />
				<button onclick="if(api){isDownload=true;api.download();}return false;">Download</button><br />
				<button onclick="if(api){api.print();}return false;">Print</button><br />
			</td>
			<td>
				<button onclick="if(api){api.setMode(api.Mode.InsertTextShape);}return false;">Text Tool</button><br />
				<button onclick="if(api){api.setMode(api.Mode.SelectText);}return false;">Select Text Tool</button><br />
				<button onclick="if(api){api.setMode(api.Mode.CropPage);}return false;">Crop Page Tool</button><br />
			</td>
			<td>
				<button onclick="fillOutForm();return false;">Fill Out Form</button><br />
				<button onclick="watermarkPages();return false;">Watermark Pages</button><br />
				<button onclick="zoomTo75();return false;">Zoom to 75%</button><br />
			</td>
		</tr>
	</tbody>
</table>
<div>
	@{
		// Get web control from ViewBag
		PdfWebControl pdfWebControl1 = ViewBag.PdfWebControl1;

		// Set control's properties
		pdfWebControl1.ID = PdfWebControlID;
		pdfWebControl1.Height = new Unit("600px");
		pdfWebControl1.Width = new Unit("100%");
		pdfWebControl1.OnClientLoad = "initRadPdf();";
		pdfWebControl1.HideBookmarks = true;
		pdfWebControl1.HideBottomBar = true;
		pdfWebControl1.HideDownloadButton = true;
		pdfWebControl1.HideObjectPropertiesBar = true;
		pdfWebControl1.HideSearchText = true;
		pdfWebControl1.HideSideBar = true;
		pdfWebControl1.HideThumbnails = true;
		pdfWebControl1.HideToolsTabs = true;
		pdfWebControl1.HideTopBar = true;
		pdfWebControl1.ViewerPageLayoutDefault = ViewerPageLayout.SinglePageContinuous;
		
		// Render web control to body
		@Html.Raw(pdfWebControl1.RenderControl())
	}
</div>
<div style="text-align:center;">
	<button onclick="if(api){api.setView( { 'page' : api.getView().page - 1 } );}return false;">Previous Page</button>
	<span id="pageInformation" style="padding:0px 5px;"></span>
	<button onclick="if(api){api.setView( { 'page' : api.getView().page + 1 } );}return false;">Next Page</button>
</div>

CS_MVC4/Views/Home/Index.cshtml
@{
	ViewBag.Title = "RAD PDF Samples";
}

<h1>RAD PDF Samples</h1>
<ul>
	<li><a href="@Url.Action("", "Basic")">Basic</a></li>
	<li><a href="@Url.Action("", "Customized")">Customized</a></li>
</ul>

<h2>Notes for use with MVC:</h2>
<ul>
	<li>An ignore route must be added so that the RAD PDF HTTP Handler is accessible, see <i>Global.asax.cs</i>.</li>
	<li>Your layout view must be updated to include the output of RenderHead() in the &lt;head&gt; element, see <i>/Views/Shared/_Layout.cshtml</i>.</li>
</ul>

CS_MVC4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>

	@Html.Raw(RadPdf.Web.UI.PdfWebControl.RenderHead())
</head>

<body>
	@RenderBody()
</body>
</html>